### ISSUE TITLE
Update for v11?

### ISSUE THREAD

**Issue by ddbrown30** [earlSt1/vtt-compendium-hider#1]
With the compendium folders module being killed by built in folders, have you considered bringing back this module for v11? This still appears to be a bit of functionality that is missing from core Foundry.

**Comment by earlSt1** [comment]
Hi, i havent got plans to update this module for v11. This module really just boils down to a CSS ruleset for hiding elements, which you can achieve with the Custom CSS module.

Here's an example snippet which you can use:
```css
li.compendium[data-pack="{{packCode}}"]{
  display:none !important
}
```

I tested with the Custom CSS module using the above snippet and it worked, so i'll close this issue for the time being. If you need any help with getting this workaround to work though feel free to add comments on this issue.
